
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phavahdquovvenvffiie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoYXZhaGRxdW92dmVudmZmaWllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5Njc2MzQsImV4cCI6MjA2NDU0MzYzNH0.B2Ov2yPL0H_52Lzm8XZZxpP12LKvJi_JQA8NsmxbpwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
